---
- name: install and configure nginx
  hosts: testServer
  remote_user: ec2-user
  become: yes

  vars:
    server_port: 8080

  tasks:
    - name: install nginx
      yum: name=nginx state=latest

    - name: create nginx configuration file
      template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
      notify: restart nginx

    - name: start nginx service
      service: name=nginx state=started enabled=yes

  handlers: 
    - name: restart nginx
      service: name=nginx state=restarted     
  

