---
- name: install and configure nginx
  hosts: testServer
  remote_user: ec2-user
  become: yes

  vars:
    server_port: 80

  tasks:
    - name: install nginx
      yum: name=nginx state=latest

    - name: create nginx configuration file
      template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
      notify: restart nginx

    - name: create empty directory
      file:
        state: directory
        path: /usr/share/nginx/helloworld

    - name: create index.html
      copy:
        src: index.html
        dest: /usr/share/nginx/helloworld/index.html
        owner: root
        group: root
        mode: '0755'

    - name: start nginx service
      service: name=nginx state=started enabled=yes

    - name: test nginx started
      debug:
        msg: nginx_started

    - name: get current http stats
      nginx_status_info:
        url: http://localhost/nginx_status
        timeout: 20

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
  

